// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access_keys.sql

package models

import (
	"context"
)

const createAccessKey = `-- name: CreateAccessKey :exec
INSERT INTO access_keys (
    id, account_id, machine_id, session_id, data, data_version
) VALUES (
    ?, ?, ?, ?, ?, ?
)
`

type CreateAccessKeyParams struct {
	ID          string `json:"id"`
	AccountID   string `json:"account_id"`
	MachineID   string `json:"machine_id"`
	SessionID   string `json:"session_id"`
	Data        string `json:"data"`
	DataVersion int64  `json:"data_version"`
}

func (q *Queries) CreateAccessKey(ctx context.Context, arg CreateAccessKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAccessKey,
		arg.ID,
		arg.AccountID,
		arg.MachineID,
		arg.SessionID,
		arg.Data,
		arg.DataVersion,
	)
	return err
}

const getAccessKey = `-- name: GetAccessKey :one
SELECT id, account_id, machine_id, session_id, data, data_version, created_at, updated_at
FROM access_keys
WHERE account_id = ? AND machine_id = ? AND session_id = ?
LIMIT 1
`

type GetAccessKeyParams struct {
	AccountID string `json:"account_id"`
	MachineID string `json:"machine_id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) GetAccessKey(ctx context.Context, arg GetAccessKeyParams) (AccessKey, error) {
	row := q.db.QueryRowContext(ctx, getAccessKey, arg.AccountID, arg.MachineID, arg.SessionID)
	var i AccessKey
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.MachineID,
		&i.SessionID,
		&i.Data,
		&i.DataVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessionIDsForMachine = `-- name: ListSessionIDsForMachine :many
SELECT session_id
FROM access_keys
WHERE account_id = ? AND machine_id = ?
`

type ListSessionIDsForMachineParams struct {
	AccountID string `json:"account_id"`
	MachineID string `json:"machine_id"`
}

func (q *Queries) ListSessionIDsForMachine(ctx context.Context, arg ListSessionIDsForMachineParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSessionIDsForMachine, arg.AccountID, arg.MachineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var session_id string
		if err := rows.Scan(&session_id); err != nil {
			return nil, err
		}
		items = append(items, session_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccessKey = `-- name: UpdateAccessKey :execrows
UPDATE access_keys
SET data = ?, data_version = ?, updated_at = CURRENT_TIMESTAMP
WHERE account_id = ? AND machine_id = ? AND session_id = ? AND data_version = ?
`

type UpdateAccessKeyParams struct {
	Data          string `json:"data"`
	DataVersion   int64  `json:"data_version"`
	AccountID     string `json:"account_id"`
	MachineID     string `json:"machine_id"`
	SessionID     string `json:"session_id"`
	DataVersion_2 int64  `json:"data_version_2"`
}

func (q *Queries) UpdateAccessKey(ctx context.Context, arg UpdateAccessKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAccessKey,
		arg.Data,
		arg.DataVersion,
		arg.AccountID,
		arg.MachineID,
		arg.SessionID,
		arg.DataVersion_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
