// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package models

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    id, public_key
) VALUES (?, ?)
RETURNING id, public_key, seq, feed_seq, created_at, updated_at, settings, settings_version, first_name, last_name, username, avatar_url, avatar_width, avatar_height, avatar_thumbhash
`

type CreateAccountParams struct {
	ID        string `json:"id"`
	PublicKey string `json:"public_key"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.ID, arg.PublicKey)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.Seq,
		&i.FeedSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
		&i.SettingsVersion,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.AvatarUrl,
		&i.AvatarWidth,
		&i.AvatarHeight,
		&i.AvatarThumbhash,
	)
	return i, err
}

const deleteAccountAvatar = `-- name: DeleteAccountAvatar :exec
UPDATE accounts
SET avatar_url = NULL, avatar_width = NULL, avatar_height = NULL, avatar_thumbhash = NULL
WHERE id = ?
`

func (q *Queries) DeleteAccountAvatar(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAccountAvatar, id)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, public_key, seq, feed_seq, created_at, updated_at, settings, settings_version, first_name, last_name, username, avatar_url, avatar_width, avatar_height, avatar_thumbhash FROM accounts WHERE id = ? LIMIT 1
`

func (q *Queries) GetAccountByID(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.Seq,
		&i.FeedSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
		&i.SettingsVersion,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.AvatarUrl,
		&i.AvatarWidth,
		&i.AvatarHeight,
		&i.AvatarThumbhash,
	)
	return i, err
}

const getAccountByPublicKey = `-- name: GetAccountByPublicKey :one
SELECT id, public_key, seq, feed_seq, created_at, updated_at, settings, settings_version, first_name, last_name, username, avatar_url, avatar_width, avatar_height, avatar_thumbhash FROM accounts WHERE public_key = ? LIMIT 1
`

func (q *Queries) GetAccountByPublicKey(ctx context.Context, publicKey string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByPublicKey, publicKey)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.Seq,
		&i.FeedSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
		&i.SettingsVersion,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.AvatarUrl,
		&i.AvatarWidth,
		&i.AvatarHeight,
		&i.AvatarThumbhash,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, public_key, seq, feed_seq, created_at, updated_at, settings, settings_version, first_name, last_name, username, avatar_url, avatar_width, avatar_height, avatar_thumbhash FROM accounts WHERE username = ? LIMIT 1
`

func (q *Queries) GetAccountByUsername(ctx context.Context, username sql.NullString) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByUsername, username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.Seq,
		&i.FeedSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
		&i.SettingsVersion,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.AvatarUrl,
		&i.AvatarWidth,
		&i.AvatarHeight,
		&i.AvatarThumbhash,
	)
	return i, err
}

const updateAccountAvatar = `-- name: UpdateAccountAvatar :exec
UPDATE accounts
SET avatar_url = ?, avatar_width = ?, avatar_height = ?, avatar_thumbhash = ?
WHERE id = ?
`

type UpdateAccountAvatarParams struct {
	AvatarUrl       sql.NullString `json:"avatar_url"`
	AvatarWidth     sql.NullInt64  `json:"avatar_width"`
	AvatarHeight    sql.NullInt64  `json:"avatar_height"`
	AvatarThumbhash sql.NullString `json:"avatar_thumbhash"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateAccountAvatar(ctx context.Context, arg UpdateAccountAvatarParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountAvatar,
		arg.AvatarUrl,
		arg.AvatarWidth,
		arg.AvatarHeight,
		arg.AvatarThumbhash,
		arg.ID,
	)
	return err
}

const updateAccountFeedSeq = `-- name: UpdateAccountFeedSeq :one
UPDATE accounts
SET feed_seq = feed_seq + 1
WHERE id = ?
RETURNING feed_seq
`

func (q *Queries) UpdateAccountFeedSeq(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, updateAccountFeedSeq, id)
	var feed_seq int64
	err := row.Scan(&feed_seq)
	return feed_seq, err
}

const updateAccountProfile = `-- name: UpdateAccountProfile :exec
UPDATE accounts
SET first_name = ?, last_name = ?, username = ?
WHERE id = ?
`

type UpdateAccountProfileParams struct {
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	Username  sql.NullString `json:"username"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountProfile,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.ID,
	)
	return err
}

const updateAccountSeq = `-- name: UpdateAccountSeq :one
UPDATE accounts
SET seq = seq + 1
WHERE id = ?
RETURNING seq
`

func (q *Queries) UpdateAccountSeq(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, updateAccountSeq, id)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const updateAccountSettings = `-- name: UpdateAccountSettings :exec
UPDATE accounts
SET settings = ?, settings_version = ?
WHERE id = ? AND settings_version = ?
`

type UpdateAccountSettingsParams struct {
	Settings          sql.NullString `json:"settings"`
	SettingsVersion   int64          `json:"settings_version"`
	ID                string         `json:"id"`
	SettingsVersion_2 int64          `json:"settings_version_2"`
}

func (q *Queries) UpdateAccountSettings(ctx context.Context, arg UpdateAccountSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountSettings,
		arg.Settings,
		arg.SettingsVersion,
		arg.ID,
		arg.SettingsVersion_2,
	)
	return err
}
