// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package models

import (
	"context"
	"database/sql"
)

const createAccountAuthRequest = `-- name: CreateAccountAuthRequest :one
INSERT INTO account_auth_requests (
    id, public_key
) VALUES (?, ?)
RETURNING id, public_key, response, response_account_id, created_at, updated_at
`

type CreateAccountAuthRequestParams struct {
	ID        string `json:"id"`
	PublicKey string `json:"public_key"`
}

func (q *Queries) CreateAccountAuthRequest(ctx context.Context, arg CreateAccountAuthRequestParams) (AccountAuthRequest, error) {
	row := q.db.QueryRowContext(ctx, createAccountAuthRequest, arg.ID, arg.PublicKey)
	var i AccountAuthRequest
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.Response,
		&i.ResponseAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTerminalAuthRequest = `-- name: CreateTerminalAuthRequest :one
INSERT INTO terminal_auth_requests (
    id, public_key
) VALUES (?, ?)
RETURNING id, public_key, response, response_account_id, created_at, updated_at
`

type CreateTerminalAuthRequestParams struct {
	ID        string `json:"id"`
	PublicKey string `json:"public_key"`
}

func (q *Queries) CreateTerminalAuthRequest(ctx context.Context, arg CreateTerminalAuthRequestParams) (TerminalAuthRequest, error) {
	row := q.db.QueryRowContext(ctx, createTerminalAuthRequest, arg.ID, arg.PublicKey)
	var i TerminalAuthRequest
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.Response,
		&i.ResponseAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOldAccountAuthRequests = `-- name: DeleteOldAccountAuthRequests :exec
DELETE FROM account_auth_requests
WHERE created_at < datetime('now', '-1 hour')
`

func (q *Queries) DeleteOldAccountAuthRequests(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOldAccountAuthRequests)
	return err
}

const deleteOldTerminalAuthRequests = `-- name: DeleteOldTerminalAuthRequests :exec
DELETE FROM terminal_auth_requests
WHERE created_at < datetime('now', '-1 hour')
`

func (q *Queries) DeleteOldTerminalAuthRequests(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOldTerminalAuthRequests)
	return err
}

const getAccountAuthRequest = `-- name: GetAccountAuthRequest :one
SELECT id, public_key, response, response_account_id, created_at, updated_at FROM account_auth_requests
WHERE public_key = ?
LIMIT 1
`

func (q *Queries) GetAccountAuthRequest(ctx context.Context, publicKey string) (AccountAuthRequest, error) {
	row := q.db.QueryRowContext(ctx, getAccountAuthRequest, publicKey)
	var i AccountAuthRequest
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.Response,
		&i.ResponseAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTerminalAuthRequest = `-- name: GetTerminalAuthRequest :one
SELECT id, public_key, response, response_account_id, created_at, updated_at FROM terminal_auth_requests
WHERE public_key = ?
LIMIT 1
`

func (q *Queries) GetTerminalAuthRequest(ctx context.Context, publicKey string) (TerminalAuthRequest, error) {
	row := q.db.QueryRowContext(ctx, getTerminalAuthRequest, publicKey)
	var i TerminalAuthRequest
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.Response,
		&i.ResponseAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountAuthResponse = `-- name: UpdateAccountAuthResponse :exec
UPDATE account_auth_requests
SET response = ?, response_account_id = ?
WHERE public_key = ?
`

type UpdateAccountAuthResponseParams struct {
	Response          sql.NullString `json:"response"`
	ResponseAccountID sql.NullString `json:"response_account_id"`
	PublicKey         string         `json:"public_key"`
}

func (q *Queries) UpdateAccountAuthResponse(ctx context.Context, arg UpdateAccountAuthResponseParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountAuthResponse, arg.Response, arg.ResponseAccountID, arg.PublicKey)
	return err
}

const updateTerminalAuthResponse = `-- name: UpdateTerminalAuthResponse :exec
UPDATE terminal_auth_requests
SET response = ?, response_account_id = ?
WHERE public_key = ?
`

type UpdateTerminalAuthResponseParams struct {
	Response          sql.NullString `json:"response"`
	ResponseAccountID sql.NullString `json:"response_account_id"`
	PublicKey         string         `json:"public_key"`
}

func (q *Queries) UpdateTerminalAuthResponse(ctx context.Context, arg UpdateTerminalAuthResponseParams) error {
	_, err := q.db.ExecContext(ctx, updateTerminalAuthResponse, arg.Response, arg.ResponseAccountID, arg.PublicKey)
	return err
}
