// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_challenges.sql

package models

import (
	"context"
	"time"
)

const createAuthChallenge = `-- name: CreateAuthChallenge :exec
INSERT INTO auth_challenges (
    id, public_key, challenge, expires_at
) VALUES (?, ?, ?, ?)
`

type CreateAuthChallengeParams struct {
	ID        string    `json:"id"`
	PublicKey string    `json:"public_key"`
	Challenge []byte    `json:"challenge"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateAuthChallenge(ctx context.Context, arg CreateAuthChallengeParams) error {
	_, err := q.db.ExecContext(ctx, createAuthChallenge,
		arg.ID,
		arg.PublicKey,
		arg.Challenge,
		arg.ExpiresAt,
	)
	return err
}

const deleteAuthChallenge = `-- name: DeleteAuthChallenge :exec
DELETE FROM auth_challenges
WHERE id = ?
`

func (q *Queries) DeleteAuthChallenge(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthChallenge, id)
	return err
}

const deleteExpiredAuthChallenges = `-- name: DeleteExpiredAuthChallenges :exec
DELETE FROM auth_challenges
WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredAuthChallenges(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAuthChallenges)
	return err
}

const getAuthChallenge = `-- name: GetAuthChallenge :one
SELECT id, public_key, challenge, expires_at, created_at
FROM auth_challenges
WHERE id = ? AND public_key = ?
LIMIT 1
`

type GetAuthChallengeParams struct {
	ID        string `json:"id"`
	PublicKey string `json:"public_key"`
}

func (q *Queries) GetAuthChallenge(ctx context.Context, arg GetAuthChallengeParams) (AuthChallenge, error) {
	row := q.db.QueryRowContext(ctx, getAuthChallenge, arg.ID, arg.PublicKey)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.Challenge,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
