// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed.sql

package models

import (
	"context"
	"database/sql"
)

const createFeedItem = `-- name: CreateFeedItem :exec
INSERT INTO user_feed_items (
    id, user_id, counter, repeat_key, body
) VALUES (
    ?, ?, ?, ?, ?
)
`

type CreateFeedItemParams struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	Counter   int64          `json:"counter"`
	RepeatKey sql.NullString `json:"repeat_key"`
	Body      string         `json:"body"`
}

func (q *Queries) CreateFeedItem(ctx context.Context, arg CreateFeedItemParams) error {
	_, err := q.db.ExecContext(ctx, createFeedItem,
		arg.ID,
		arg.UserID,
		arg.Counter,
		arg.RepeatKey,
		arg.Body,
	)
	return err
}

const deleteFeedItemsByRepeatKey = `-- name: DeleteFeedItemsByRepeatKey :exec
DELETE FROM user_feed_items
WHERE user_id = ? AND repeat_key = ?
`

type DeleteFeedItemsByRepeatKeyParams struct {
	UserID    string         `json:"user_id"`
	RepeatKey sql.NullString `json:"repeat_key"`
}

func (q *Queries) DeleteFeedItemsByRepeatKey(ctx context.Context, arg DeleteFeedItemsByRepeatKeyParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedItemsByRepeatKey, arg.UserID, arg.RepeatKey)
	return err
}

const listFeedItems = `-- name: ListFeedItems :many
SELECT id, user_id, counter, repeat_key, body, created_at
FROM user_feed_items
WHERE user_id = ?
  AND (? IS NULL OR counter < ?)
  AND (? IS NULL OR counter > ?)
ORDER BY counter DESC
LIMIT ?
`

type ListFeedItemsParams struct {
	UserID    string      `json:"user_id"`
	Column2   interface{} `json:"column_2"`
	Counter   int64       `json:"counter"`
	Column4   interface{} `json:"column_4"`
	Counter_2 int64       `json:"counter_2"`
	Limit     int64       `json:"limit"`
}

func (q *Queries) ListFeedItems(ctx context.Context, arg ListFeedItemsParams) ([]UserFeedItem, error) {
	rows, err := q.db.QueryContext(ctx, listFeedItems,
		arg.UserID,
		arg.Column2,
		arg.Counter,
		arg.Column4,
		arg.Counter_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserFeedItem{}
	for rows.Next() {
		var i UserFeedItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Counter,
			&i.RepeatKey,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
