// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kv.sql

package models

import (
	"context"
	"database/sql"
)

const deleteKV = `-- name: DeleteKV :exec
DELETE FROM user_kv_store
WHERE account_id = ? AND key = ? AND version = ? - 1
`

type DeleteKVParams struct {
	AccountID string      `json:"account_id"`
	Key       string      `json:"key"`
	Column3   interface{} `json:"column_3"`
}

func (q *Queries) DeleteKV(ctx context.Context, arg DeleteKVParams) error {
	_, err := q.db.ExecContext(ctx, deleteKV, arg.AccountID, arg.Key, arg.Column3)
	return err
}

const getKV = `-- name: GetKV :one
SELECT id, account_id, key, value, version, created_at, updated_at
FROM user_kv_store
WHERE account_id = ? AND key = ?
LIMIT 1
`

type GetKVParams struct {
	AccountID string `json:"account_id"`
	Key       string `json:"key"`
}

func (q *Queries) GetKV(ctx context.Context, arg GetKVParams) (UserKvStore, error) {
	row := q.db.QueryRowContext(ctx, getKV, arg.AccountID, arg.Key)
	var i UserKvStore
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Key,
		&i.Value,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listKV = `-- name: ListKV :many
SELECT id, account_id, key, value, version, created_at, updated_at
FROM user_kv_store
WHERE account_id = ?
  AND (? = '' OR key LIKE ? || '%')
ORDER BY key
LIMIT ?
`

type ListKVParams struct {
	AccountID string         `json:"account_id"`
	Column2   interface{}    `json:"column_2"`
	Column3   sql.NullString `json:"column_3"`
	Limit     int64          `json:"limit"`
}

func (q *Queries) ListKV(ctx context.Context, arg ListKVParams) ([]UserKvStore, error) {
	rows, err := q.db.QueryContext(ctx, listKV,
		arg.AccountID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserKvStore{}
	for rows.Next() {
		var i UserKvStore
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Key,
			&i.Value,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertKV = `-- name: UpsertKV :exec
INSERT INTO user_kv_store (id, account_id, key, value, version, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(account_id, key)
DO UPDATE SET
    value = excluded.value,
    version = excluded.version,
    updated_at = CURRENT_TIMESTAMP
WHERE user_kv_store.version = excluded.version - 1
`

type UpsertKVParams struct {
	ID        string         `json:"id"`
	AccountID string         `json:"account_id"`
	Key       string         `json:"key"`
	Value     sql.NullString `json:"value"`
	Version   int64          `json:"version"`
}

func (q *Queries) UpsertKV(ctx context.Context, arg UpsertKVParams) error {
	_, err := q.db.ExecContext(ctx, upsertKV,
		arg.ID,
		arg.AccountID,
		arg.Key,
		arg.Value,
		arg.Version,
	)
	return err
}
