// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: machines.sql

package models

import (
	"context"
	"database/sql"
	"time"
)

const createMachine = `-- name: CreateMachine :exec
INSERT INTO machines (
    id, account_id, metadata, metadata_version,
    daemon_state, daemon_state_version, data_encryption_key
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateMachineParams struct {
	ID                 string         `json:"id"`
	AccountID          string         `json:"account_id"`
	Metadata           string         `json:"metadata"`
	MetadataVersion    int64          `json:"metadata_version"`
	DaemonState        sql.NullString `json:"daemon_state"`
	DaemonStateVersion int64          `json:"daemon_state_version"`
	DataEncryptionKey  []byte         `json:"data_encryption_key"`
}

func (q *Queries) CreateMachine(ctx context.Context, arg CreateMachineParams) error {
	_, err := q.db.ExecContext(ctx, createMachine,
		arg.ID,
		arg.AccountID,
		arg.Metadata,
		arg.MetadataVersion,
		arg.DaemonState,
		arg.DaemonStateVersion,
		arg.DataEncryptionKey,
	)
	return err
}

const deleteMachine = `-- name: DeleteMachine :exec
DELETE FROM machines WHERE account_id = ? AND id = ?
`

type DeleteMachineParams struct {
	AccountID string `json:"account_id"`
	ID        string `json:"id"`
}

func (q *Queries) DeleteMachine(ctx context.Context, arg DeleteMachineParams) error {
	_, err := q.db.ExecContext(ctx, deleteMachine, arg.AccountID, arg.ID)
	return err
}

const getMachine = `-- name: GetMachine :one
SELECT id, account_id, metadata, metadata_version, daemon_state, daemon_state_version, data_encryption_key, seq, active, last_active_at, created_at, updated_at FROM machines
WHERE account_id = ? AND id = ?
LIMIT 1
`

type GetMachineParams struct {
	AccountID string `json:"account_id"`
	ID        string `json:"id"`
}

func (q *Queries) GetMachine(ctx context.Context, arg GetMachineParams) (Machine, error) {
	row := q.db.QueryRowContext(ctx, getMachine, arg.AccountID, arg.ID)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Metadata,
		&i.MetadataVersion,
		&i.DaemonState,
		&i.DaemonStateVersion,
		&i.DataEncryptionKey,
		&i.Seq,
		&i.Active,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMachines = `-- name: ListMachines :many
SELECT id, account_id, metadata, metadata_version, daemon_state, daemon_state_version, data_encryption_key, seq, active, last_active_at, created_at, updated_at FROM machines
WHERE account_id = ?
ORDER BY last_active_at DESC
`

func (q *Queries) ListMachines(ctx context.Context, accountID string) ([]Machine, error) {
	rows, err := q.db.QueryContext(ctx, listMachines, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Machine{}
	for rows.Next() {
		var i Machine
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Metadata,
			&i.MetadataVersion,
			&i.DaemonState,
			&i.DaemonStateVersion,
			&i.DataEncryptionKey,
			&i.Seq,
			&i.Active,
			&i.LastActiveAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMachineActivity = `-- name: UpdateMachineActivity :exec
UPDATE machines
SET active = ?, last_active_at = ?
WHERE account_id = ? AND id = ?
`

type UpdateMachineActivityParams struct {
	Active       int64     `json:"active"`
	LastActiveAt time.Time `json:"last_active_at"`
	AccountID    string    `json:"account_id"`
	ID           string    `json:"id"`
}

func (q *Queries) UpdateMachineActivity(ctx context.Context, arg UpdateMachineActivityParams) error {
	_, err := q.db.ExecContext(ctx, updateMachineActivity,
		arg.Active,
		arg.LastActiveAt,
		arg.AccountID,
		arg.ID,
	)
	return err
}

const updateMachineDaemonState = `-- name: UpdateMachineDaemonState :execrows
UPDATE machines
SET daemon_state = ?, daemon_state_version = ?
WHERE account_id = ? AND id = ? AND daemon_state_version = ?
`

type UpdateMachineDaemonStateParams struct {
	DaemonState          sql.NullString `json:"daemon_state"`
	DaemonStateVersion   int64          `json:"daemon_state_version"`
	AccountID            string         `json:"account_id"`
	ID                   string         `json:"id"`
	DaemonStateVersion_2 int64          `json:"daemon_state_version_2"`
}

func (q *Queries) UpdateMachineDaemonState(ctx context.Context, arg UpdateMachineDaemonStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMachineDaemonState,
		arg.DaemonState,
		arg.DaemonStateVersion,
		arg.AccountID,
		arg.ID,
		arg.DaemonStateVersion_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMachineMetadata = `-- name: UpdateMachineMetadata :execrows
UPDATE machines
SET metadata = ?, metadata_version = ?
WHERE account_id = ? AND id = ? AND metadata_version = ?
`

type UpdateMachineMetadataParams struct {
	Metadata          string `json:"metadata"`
	MetadataVersion   int64  `json:"metadata_version"`
	AccountID         string `json:"account_id"`
	ID                string `json:"id"`
	MetadataVersion_2 int64  `json:"metadata_version_2"`
}

func (q *Queries) UpdateMachineMetadata(ctx context.Context, arg UpdateMachineMetadataParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMachineMetadata,
		arg.Metadata,
		arg.MetadataVersion,
		arg.AccountID,
		arg.ID,
		arg.MetadataVersion_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMachineSeq = `-- name: UpdateMachineSeq :one
UPDATE machines
SET seq = seq + 1
WHERE account_id = ? AND id = ?
RETURNING seq
`

type UpdateMachineSeqParams struct {
	AccountID string `json:"account_id"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateMachineSeq(ctx context.Context, arg UpdateMachineSeqParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, updateMachineSeq, arg.AccountID, arg.ID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}
