// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package models

import (
	"context"
	"database/sql"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO session_messages (
    id, session_id, local_id, seq, content
) VALUES (?, ?, ?, ?, ?)
RETURNING id, session_id, local_id, seq, content, created_at, updated_at
`

type CreateMessageParams struct {
	ID        string         `json:"id"`
	SessionID string         `json:"session_id"`
	LocalID   sql.NullString `json:"local_id"`
	Seq       int64          `json:"seq"`
	Content   string         `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (SessionMessage, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.SessionID,
		arg.LocalID,
		arg.Seq,
		arg.Content,
	)
	var i SessionMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.LocalID,
		&i.Seq,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSessionMessages = `-- name: DeleteSessionMessages :exec
DELETE FROM session_messages WHERE session_id = ?
`

func (q *Queries) DeleteSessionMessages(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionMessages, sessionID)
	return err
}

const getLatestMessageSeq = `-- name: GetLatestMessageSeq :one
SELECT COALESCE(MAX(seq), 0) as max_seq
FROM session_messages
WHERE session_id = ?
`

func (q *Queries) GetLatestMessageSeq(ctx context.Context, sessionID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLatestMessageSeq, sessionID)
	var max_seq interface{}
	err := row.Scan(&max_seq)
	return max_seq, err
}

const getMessageByLocalID = `-- name: GetMessageByLocalID :one
SELECT id, session_id, local_id, seq, content, created_at, updated_at FROM session_messages
WHERE session_id = ? AND local_id = ?
LIMIT 1
`

type GetMessageByLocalIDParams struct {
	SessionID string         `json:"session_id"`
	LocalID   sql.NullString `json:"local_id"`
}

func (q *Queries) GetMessageByLocalID(ctx context.Context, arg GetMessageByLocalIDParams) (SessionMessage, error) {
	row := q.db.QueryRowContext(ctx, getMessageByLocalID, arg.SessionID, arg.LocalID)
	var i SessionMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.LocalID,
		&i.Seq,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, session_id, local_id, seq, content, created_at, updated_at FROM session_messages
WHERE session_id = ?
ORDER BY seq ASC
LIMIT ? OFFSET ?
`

type ListMessagesParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]SessionMessage, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, arg.SessionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionMessage{}
	for rows.Next() {
		var i SessionMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.LocalID,
			&i.Seq,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
