// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
	"time"
)

type AccessKey struct {
	ID          string    `json:"id"`
	AccountID   string    `json:"account_id"`
	MachineID   string    `json:"machine_id"`
	SessionID   string    `json:"session_id"`
	Data        string    `json:"data"`
	DataVersion int64     `json:"data_version"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Account struct {
	ID              string         `json:"id"`
	PublicKey       string         `json:"public_key"`
	Seq             int64          `json:"seq"`
	FeedSeq         int64          `json:"feed_seq"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	Settings        sql.NullString `json:"settings"`
	SettingsVersion int64          `json:"settings_version"`
	FirstName       sql.NullString `json:"first_name"`
	LastName        sql.NullString `json:"last_name"`
	Username        sql.NullString `json:"username"`
	AvatarUrl       sql.NullString `json:"avatar_url"`
	AvatarWidth     sql.NullInt64  `json:"avatar_width"`
	AvatarHeight    sql.NullInt64  `json:"avatar_height"`
	AvatarThumbhash sql.NullString `json:"avatar_thumbhash"`
}

type AccountAuthRequest struct {
	ID                string         `json:"id"`
	PublicKey         string         `json:"public_key"`
	Response          sql.NullString `json:"response"`
	ResponseAccountID sql.NullString `json:"response_account_id"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type AccountPushToken struct {
	ID        string    `json:"id"`
	AccountID string    `json:"account_id"`
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Artifact struct {
	ID                string    `json:"id"`
	AccountID         string    `json:"account_id"`
	Header            []byte    `json:"header"`
	HeaderVersion     int64     `json:"header_version"`
	Body              []byte    `json:"body"`
	BodyVersion       int64     `json:"body_version"`
	DataEncryptionKey []byte    `json:"data_encryption_key"`
	Seq               int64     `json:"seq"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type Machine struct {
	ID                 string         `json:"id"`
	AccountID          string         `json:"account_id"`
	Metadata           string         `json:"metadata"`
	MetadataVersion    int64          `json:"metadata_version"`
	DaemonState        sql.NullString `json:"daemon_state"`
	DaemonStateVersion int64          `json:"daemon_state_version"`
	DataEncryptionKey  []byte         `json:"data_encryption_key"`
	Seq                int64          `json:"seq"`
	Active             int64          `json:"active"`
	LastActiveAt       time.Time      `json:"last_active_at"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type Session struct {
	ID                string         `json:"id"`
	Tag               string         `json:"tag"`
	AccountID         string         `json:"account_id"`
	Metadata          string         `json:"metadata"`
	MetadataVersion   int64          `json:"metadata_version"`
	AgentState        sql.NullString `json:"agent_state"`
	AgentStateVersion int64          `json:"agent_state_version"`
	DataEncryptionKey []byte         `json:"data_encryption_key"`
	Seq               int64          `json:"seq"`
	Active            int64          `json:"active"`
	LastActiveAt      time.Time      `json:"last_active_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type SessionMessage struct {
	ID        string         `json:"id"`
	SessionID string         `json:"session_id"`
	LocalID   sql.NullString `json:"local_id"`
	Seq       int64          `json:"seq"`
	Content   string         `json:"content"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type TerminalAuthRequest struct {
	ID                string         `json:"id"`
	PublicKey         string         `json:"public_key"`
	Response          sql.NullString `json:"response"`
	ResponseAccountID sql.NullString `json:"response_account_id"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type UserFeedItem struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	Counter   int64          `json:"counter"`
	RepeatKey sql.NullString `json:"repeat_key"`
	Body      string         `json:"body"`
	CreatedAt time.Time      `json:"created_at"`
}

type UserKvStore struct {
	ID        string         `json:"id"`
	AccountID string         `json:"account_id"`
	Key       string         `json:"key"`
	Value     sql.NullString `json:"value"`
	Version   int64          `json:"version"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
