// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push_tokens.sql

package models

import (
	"context"
)

const createPushToken = `-- name: CreatePushToken :one
INSERT INTO account_push_tokens (
    id, account_id, token
) VALUES (?, ?, ?)
ON CONFLICT(account_id, token) DO UPDATE SET updated_at = CURRENT_TIMESTAMP
RETURNING id, account_id, token, created_at, updated_at
`

type CreatePushTokenParams struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
	Token     string `json:"token"`
}

func (q *Queries) CreatePushToken(ctx context.Context, arg CreatePushTokenParams) (AccountPushToken, error) {
	row := q.db.QueryRowContext(ctx, createPushToken, arg.ID, arg.AccountID, arg.Token)
	var i AccountPushToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePushToken = `-- name: DeletePushToken :exec
DELETE FROM account_push_tokens
WHERE account_id = ? AND token = ?
`

type DeletePushTokenParams struct {
	AccountID string `json:"account_id"`
	Token     string `json:"token"`
}

func (q *Queries) DeletePushToken(ctx context.Context, arg DeletePushTokenParams) error {
	_, err := q.db.ExecContext(ctx, deletePushToken, arg.AccountID, arg.Token)
	return err
}

const listPushTokens = `-- name: ListPushTokens :many
SELECT id, account_id, token, created_at, updated_at FROM account_push_tokens
WHERE account_id = ?
`

func (q *Queries) ListPushTokens(ctx context.Context, accountID string) ([]AccountPushToken, error) {
	rows, err := q.db.QueryContext(ctx, listPushTokens, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountPushToken{}
	for rows.Next() {
		var i AccountPushToken
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Token,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
