// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relationships.sql

package models

import (
	"context"
	"database/sql"
)

const getRelationship = `-- name: GetRelationship :one
SELECT from_user_id, to_user_id, status, created_at, updated_at, accepted_at, last_notified_at
FROM user_relationships
WHERE from_user_id = ? AND to_user_id = ?
LIMIT 1
`

type GetRelationshipParams struct {
	FromUserID string `json:"from_user_id"`
	ToUserID   string `json:"to_user_id"`
}

func (q *Queries) GetRelationship(ctx context.Context, arg GetRelationshipParams) (UserRelationship, error) {
	row := q.db.QueryRowContext(ctx, getRelationship, arg.FromUserID, arg.ToUserID)
	var i UserRelationship
	err := row.Scan(
		&i.FromUserID,
		&i.ToUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedAt,
		&i.LastNotifiedAt,
	)
	return i, err
}

const listRelationshipsByFrom = `-- name: ListRelationshipsByFrom :many
SELECT from_user_id, to_user_id, status, created_at, updated_at, accepted_at, last_notified_at
FROM user_relationships
WHERE from_user_id = ? AND status IN ('friend', 'pending', 'requested')
`

func (q *Queries) ListRelationshipsByFrom(ctx context.Context, fromUserID string) ([]UserRelationship, error) {
	rows, err := q.db.QueryContext(ctx, listRelationshipsByFrom, fromUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRelationship{}
	for rows.Next() {
		var i UserRelationship
		if err := rows.Scan(
			&i.FromUserID,
			&i.ToUserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedAt,
			&i.LastNotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRelationship = `-- name: UpsertRelationship :exec
INSERT INTO user_relationships (
    from_user_id, to_user_id, status, accepted_at, last_notified_at
) VALUES (
    ?, ?, ?, ?, ?
)
ON CONFLICT(from_user_id, to_user_id)
DO UPDATE SET
    status = excluded.status,
    accepted_at = excluded.accepted_at,
    last_notified_at = COALESCE(excluded.last_notified_at, user_relationships.last_notified_at),
    updated_at = CURRENT_TIMESTAMP
`

type UpsertRelationshipParams struct {
	FromUserID     string       `json:"from_user_id"`
	ToUserID       string       `json:"to_user_id"`
	Status         string       `json:"status"`
	AcceptedAt     sql.NullTime `json:"accepted_at"`
	LastNotifiedAt sql.NullTime `json:"last_notified_at"`
}

func (q *Queries) UpsertRelationship(ctx context.Context, arg UpsertRelationshipParams) error {
	_, err := q.db.ExecContext(ctx, upsertRelationship,
		arg.FromUserID,
		arg.ToUserID,
		arg.Status,
		arg.AcceptedAt,
		arg.LastNotifiedAt,
	)
	return err
}
